language: php

php:
  - 5.3
  - 5.4
  - hhvm

install:
  - pyrus channel-discover pear.symfony.com
  - pyrus install --force phpunit/DbUnit
  - composer install --dev --prefer-source

script: phpunit --coverage-text
